name: ml-ds
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - xarray
  - netcdf4
  - zarr
  - numcodecs
  - cfgrib
  - eccodes
  - xesmf=0.9
  - dask
  - pytorch
  - torchvision
  - scikit-learn
  - pytorch-lightning
  - notebook
  - ipykernel
  - cdsapi
  - pip
  - pip:
      - lightning[extra]
      - phiflow
      - -e .
